version: '3.9'
services:
  backend:
    # Dockerfileの内容を読み込む
    build: .
    ports:
      - 8000:8000
    # working directory
    volumes:
      - .:/app
    # dbの起動後にbackendを起動
    depends_on:
      - db
      - redis
    tty: true

  db:
    image: mysql:5.7.22
    container_name: ambassador_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_HOST: ambassador
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33066:3306

  redis:
    image: redis:latest
    ports:
      - 6379:6379